# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rrr/XP/pynq_dpu/pynq_dpu.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_2_0/design_1_proc_sys_reset_2_0.xci
# IP: The module: 'design_1_proc_sys_reset_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rrr/XP/pynq_dpu/pynq_dpu.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_2_0/design_1_proc_sys_reset_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_2_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/rrr/XP/pynq_dpu/pynq_dpu.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_2_0/design_1_proc_sys_reset_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/rrr/XP/pynq_dpu/pynq_dpu.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_2_0/design_1_proc_sys_reset_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/rrr/XP/pynq_dpu/pynq_dpu.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_2_0/design_1_proc_sys_reset_2_0.xci
# IP: The module: 'design_1_proc_sys_reset_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rrr/XP/pynq_dpu/pynq_dpu.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_2_0/design_1_proc_sys_reset_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/rrr/XP/pynq_dpu/pynq_dpu.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_2_0/design_1_proc_sys_reset_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/rrr/XP/pynq_dpu/pynq_dpu.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_2_0/design_1_proc_sys_reset_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_proc_sys_reset_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
