# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/pynqz2_dpu/pynqz2_dpu.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_dpu || ORIG_REF_NAME==pynqz2_dpu} -quiet] -quiet

# IP: bd/pynqz2_dpu/ip/pynqz2_dpu_dpu_eu_0_0/pynqz2_dpu_dpu_eu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_dpu_dpu_eu_0_0 || ORIG_REF_NAME==pynqz2_dpu_dpu_eu_0_0} -quiet] -quiet

# IP: bd/pynqz2_dpu/ip/pynqz2_dpu_processing_system7_0_0/pynqz2_dpu_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_dpu_processing_system7_0_0 || ORIG_REF_NAME==pynqz2_dpu_processing_system7_0_0} -quiet] -quiet

# IP: bd/pynqz2_dpu/ip/pynqz2_dpu_xlconcat_0_0/pynqz2_dpu_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_dpu_xlconcat_0_0 || ORIG_REF_NAME==pynqz2_dpu_xlconcat_0_0} -quiet] -quiet

# IP: bd/pynqz2_dpu/ip/pynqz2_dpu_proc_sys_reset_0_0/pynqz2_dpu_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_dpu_proc_sys_reset_0_0 || ORIG_REF_NAME==pynqz2_dpu_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/pynqz2_dpu/ip/pynqz2_dpu_proc_sys_reset_1_0/pynqz2_dpu_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_dpu_proc_sys_reset_1_0 || ORIG_REF_NAME==pynqz2_dpu_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/pynqz2_dpu/ip/pynqz2_dpu_proc_sys_reset_2_0/pynqz2_dpu_proc_sys_reset_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_dpu_proc_sys_reset_2_0 || ORIG_REF_NAME==pynqz2_dpu_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/pynqz2_dpu/ip/pynqz2_dpu_clk_wiz_0_0/pynqz2_dpu_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pynqz2_dpu_clk_wiz_0_0 || ORIG_REF_NAME==pynqz2_dpu_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/pynqz2_dpu/pynqz2_dpu_ooc.xdc
