# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/User/Desktop/hdldpu/hdldpu.srcs/sources_1/bd/pynqz2_dpu/ip/pynqz2_dpu_dpu_eu_0_0/pynqz2_dpu_dpu_eu_0_0.xci
# IP: The module: 'pynqz2_dpu_dpu_eu_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/User/Desktop/hdldpu/hdldpu.srcs/sources_1/bd/pynqz2_dpu/ip/pynqz2_dpu_dpu_eu_0_0/xci/sfm/fp_exp/fp_exp.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_exp || ORIG_REF_NAME==fp_exp} -quiet] -quiet

# IP: c:/Users/User/Desktop/hdldpu/hdldpu.srcs/sources_1/bd/pynqz2_dpu/ip/pynqz2_dpu_dpu_eu_0_0/xci/sfm/fp_convert/fp_convert.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_convert || ORIG_REF_NAME==fp_convert} -quiet] -quiet

# IP: c:/Users/User/Desktop/hdldpu/hdldpu.srcs/sources_1/bd/pynqz2_dpu/ip/pynqz2_dpu_dpu_eu_0_0/xci/sfm/fp_div/fp_div.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_div || ORIG_REF_NAME==fp_div} -quiet] -quiet

# IP: c:/Users/User/Desktop/hdldpu/hdldpu.srcs/sources_1/bd/pynqz2_dpu/ip/pynqz2_dpu_dpu_eu_0_0/xci/sfm/fp_acc/fp_acc.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_acc || ORIG_REF_NAME==fp_acc} -quiet] -quiet

# IP: c:/Users/User/Desktop/hdldpu/hdldpu.srcs/sources_1/bd/pynqz2_dpu/ip/pynqz2_dpu_dpu_eu_0_0/xci/sfm/fp_add/fp_add.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_add || ORIG_REF_NAME==fp_add} -quiet] -quiet

# XDC: c:/Users/User/Desktop/hdldpu/hdldpu.srcs/sources_1/bd/pynqz2_dpu/ip/pynqz2_dpu_dpu_eu_0_0/pynqz2_dpu_dpu_eu_0_0_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynqz2_dpu_dpu_eu_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/User/Desktop/hdldpu/hdldpu.srcs/sources_1/bd/pynqz2_dpu/ip/pynqz2_dpu_dpu_eu_0_0/pynqz2_dpu_dpu_eu_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynqz2_dpu_dpu_eu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/User/Desktop/hdldpu/hdldpu.srcs/sources_1/bd/pynqz2_dpu/ip/pynqz2_dpu_dpu_eu_0_0/pynqz2_dpu_dpu_eu_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynqz2_dpu_dpu_eu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/User/Desktop/hdldpu/hdldpu.srcs/sources_1/bd/pynqz2_dpu/ip/pynqz2_dpu_dpu_eu_0_0/pynqz2_dpu_dpu_eu_0_0.xci
# IP: The module: 'pynqz2_dpu_dpu_eu_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/User/Desktop/hdldpu/hdldpu.srcs/sources_1/bd/pynqz2_dpu/ip/pynqz2_dpu_dpu_eu_0_0/xci/sfm/fp_exp/fp_exp.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_exp || ORIG_REF_NAME==fp_exp} -quiet] -quiet

# IP: c:/Users/User/Desktop/hdldpu/hdldpu.srcs/sources_1/bd/pynqz2_dpu/ip/pynqz2_dpu_dpu_eu_0_0/xci/sfm/fp_convert/fp_convert.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_convert || ORIG_REF_NAME==fp_convert} -quiet] -quiet

# IP: c:/Users/User/Desktop/hdldpu/hdldpu.srcs/sources_1/bd/pynqz2_dpu/ip/pynqz2_dpu_dpu_eu_0_0/xci/sfm/fp_div/fp_div.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_div || ORIG_REF_NAME==fp_div} -quiet] -quiet

# IP: c:/Users/User/Desktop/hdldpu/hdldpu.srcs/sources_1/bd/pynqz2_dpu/ip/pynqz2_dpu_dpu_eu_0_0/xci/sfm/fp_acc/fp_acc.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_acc || ORIG_REF_NAME==fp_acc} -quiet] -quiet

# IP: c:/Users/User/Desktop/hdldpu/hdldpu.srcs/sources_1/bd/pynqz2_dpu/ip/pynqz2_dpu_dpu_eu_0_0/xci/sfm/fp_add/fp_add.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_add || ORIG_REF_NAME==fp_add} -quiet] -quiet

# XDC: c:/Users/User/Desktop/hdldpu/hdldpu.srcs/sources_1/bd/pynqz2_dpu/ip/pynqz2_dpu_dpu_eu_0_0/pynqz2_dpu_dpu_eu_0_0_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynqz2_dpu_dpu_eu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/User/Desktop/hdldpu/hdldpu.srcs/sources_1/bd/pynqz2_dpu/ip/pynqz2_dpu_dpu_eu_0_0/pynqz2_dpu_dpu_eu_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynqz2_dpu_dpu_eu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/User/Desktop/hdldpu/hdldpu.srcs/sources_1/bd/pynqz2_dpu/ip/pynqz2_dpu_dpu_eu_0_0/pynqz2_dpu_dpu_eu_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pynqz2_dpu_dpu_eu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
